projects/ideabox/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :ideas

  root 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :categories
  end

  namespace :admin do
    resources :images
  end
end

projects/ideabox/app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :user
  has_many :idea_categories
  has_many :ideas, through: :idea_categories

end

projects/ideabox/app/models/idea.rb
class Idea < ActiveRecord::Base

  validates :title, presence: true
  validates :description, presence: true

  belongs_to :user
  has_many :idea_categories
  has_many :categories, through: :idea_categories

  has_many :ideas_images
  has_many :images, through: :ideas_images
end

projects/ideabox/app/models/idea_category.rb
class IdeaCategory < ActiveRecord::Base
  belongs_to :idea
  belongs_to :category
end

projects/ideabox/app/models/idea_image.rb
class IdeaImage < ActiveRecord::Base
  belongs_to :idea
  belongs_to :image
end

projects/ideabox/app/models/ideas_image.rb
class IdeasImage < ActiveRecord::Base
  belongs_to :idea
  belongs_to :image
end

projects/ideabox/app/models/image.rb
class Image < ActiveRecord::Base
  validates :url, presence: true

  has_many :ideas_images
  has_many :ideas, through: :ideas_images
end

projects/ideabox/app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true

  has_many :ideas
  has_many :categories


  has_secure_password

  enum role: %w(default, admin)

  def admin?
    role == "admin"
  end
end

projects/ideabox/app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :require_admin

  def require_admin
    render 'errors' unless current_admin?

  end

end

projects/ideabox/app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category Created!"
      redirect_to admin_categories_path
    else
      flash[:error] = @category.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category has been updated!"
      redirect_to admin_categories_path
    else
      flash[:error] = @category.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end


  private

  def category_params
    params.require(:category).permit(:name)
  end


end

projects/ideabox/app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController

  def index
    @images = Image.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      flash[:notice] = "Image Created!"
      redirect_to admin_images_path
    else
      flash[:error] = @image.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      flash[:notice] = "image has been updated!"
      redirect_to admin_images_path
    else
      flash[:error] = @image.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to admin_images_path
  end


  private

  def image_params
    params.require(:image).permit(:url, :description)
  end


end

projects/ideabox/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end  
end

projects/ideabox/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def new
    @idea = current_user.ideas.new
    @categories = Category.all
    @images = Image.all
  end

  def index
    @ideas = current_user.ideas
  end

  def create
    @idea = current_user.ideas.new(idea_params)
    categories = params[:idea][:category_ids].reject(&:empty?)
    images = params[:idea][:image_ids].reject(&:empty?)
    if @idea.save
      flash[:notice] = "Idea created!"
      categories.each { |category| @idea.categories << Category.find(category) }
      images.each { |image| @idea.images << Image.find(image) }
      redirect_to idea_path(@idea)
    else
      flash[:error] = "Invalid entry"
      render :new
    end
  end

  def show
    @idea = current_user.ideas.find(params[:id])
  end

  def edit
      @idea = current_user.ideas.find(params[:id])
      @categories = Category.all
      @images = Image.all
    end

    def update
      @idea = current_user.ideas.find(params[:id])
      categories = params[:idea][:category_ids].reject(&:empty?)
      images = params[:idea][:image_ids].reject(&:empty?)
      if @idea.update(idea_params)
        @idea.categories.destroy_all
        @idea.images.destroy_all
        categories.each { |category| @idea.categories << Category.find(category) }
        images.each { |image| @idea.images << Image.find(image) }
        redirect_to idea_path(@idea)
      else
        render :edit
      end
    end

    def destroy
      @idea = current_user.ideas.find(params[:id])
      @idea.destroy
      redirect_to ideas_path
    end

  private

  def idea_params
    params.require(:idea).permit(:title, :description)
  end

end

projects/ideabox/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(username: params[:session][:username])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash[:errors] = "Invalid login"
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Successfully logged out!"
    redirect_to login_path
  end

end

projects/ideabox/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Ideabox account created!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show

  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :password_confirmation)
  end

end

projects/ideabox/app/helpers/application_helper.rb
module ApplicationHelper
end

projects/ideabox/app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= f.text_field :name, placeholder: "Name" %><br>
  <%= f.submit %>
<% end %>

projects/ideabox/app/views/admin/categories/edit.html.erb
<%= render 'form' %>

projects/ideabox/app/views/admin/categories/index.html.erb
<h1> Categories: </h1>

<ul>
<% @categories.each do |category| %>
  <li>name: <%= category.name %><br>
  <%= link_to "edit", edit_admin_category_path(category) %>
  <%= link_to "delete", admin_category_path(category), method: "delete" %></li>
<% end %>
</ul>

projects/ideabox/app/views/admin/categories/show.html.erb
<h1> <%= @category.description %> </h1>

<%= link_to "Edit", edit_admin_category_path(@category)%>

<%= link_to "Delete", admin_category_path(@category), method: :delete %>

projects/ideabox/app/views/admin/images/_form.html.erb
<%= form_for [:admin, @image] do |f| %>
  <%= f.text_field :url, placeholder: "Image URL" %><br>
  <%= f.text_field :description, placeholder: "Description" %><br>
  <%= f.submit %>
<% end %>

projects/ideabox/app/views/admin/images/edit.html.erb
<%= render partial: 'form' %>

projects/ideabox/app/views/admin/images/errors.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style>
  body {
    background-color: #EFEFEF;
    color: #2E2F30;
    text-align: center;
    font-family: arial, sans-serif;
    margin: 0;
  }

  div.dialog {
    width: 95%;
    max-width: 33em;
    margin: 4em auto 0;
  }

  div.dialog > div {
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #BBB;
    border-top: #B00100 solid 4px;
    border-top-left-radius: 9px;
    border-top-right-radius: 9px;
    background-color: white;
    padding: 7px 12% 0;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }

  h1 {
    font-size: 100%;
    color: #730E15;
    line-height: 1.5em;
  }

  div.dialog > p {
    margin: 0 0 1em;
    padding: 1em;
    background-color: #F7F7F7;
    border: 1px solid #CCC;
    border-right-color: #999;
    border-left-color: #999;
    border-bottom-color: #999;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    border-top-color: #DADADA;
    color: #666;
    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
  }
  </style>
</head>

<body>
  <!-- This file lives in public/404.html -->
  <div class="dialog">
    <div>
      <h1>The page you were looking for doesn't exist.</h1>
      <p>You may have mistyped the address or the page may have moved.</p>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>

projects/ideabox/app/views/admin/images/index.html.erb
<% @images.each do |image| %>
  <br><img src=<%= image.url %> height="100" width="125"><br>
  Description: <%= image.description %> <br>
  <%= link_to "edit", edit_admin_image_path(image) %>
  <%= link_to "delete", admin_image_path(image), method: "delete" %>
<% end %>

projects/ideabox/app/views/admin/images/new.html.erb
<%= render partial: 'form' %>

projects/ideabox/app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <%= f.text_field :title, placeholder: "Title" %><br>
  <%= f.text_field :description, placeholder: "Description" %><br>
  Categories: <%= f.collection_check_boxes(:category_ids, @categories, :id, :name) %><br>
  Images: <%= f.collection_check_boxes(:image_ids, @images, :id, :description) %><br>
  <%= f.submit %>
<% end %>

projects/ideabox/app/views/ideas/edit.html.erb
<%= render 'form' %>

projects/ideabox/app/views/ideas/index.html.erb
<br><%= link_to "Create a new idea!", new_idea_path %><br>

<h1>My Ideas: </h1>

<% @ideas.each do |idea| %>
  <%= link_to idea.title, idea_path(idea) %><br>
  description: <%= idea.description %> <br>
  <%= link_to "Edit", edit_idea_path(idea) %><br>
  <%= link_to "Delete", idea_path(idea), method: "delete"  %>

<% end %>

projects/ideabox/app/views/ideas/new.html.erb
<%= render 'form' %>

projects/ideabox/app/views/ideas/show.html.erb
<h1> <%= @idea.title %> </h1>
<p> <%= @idea.description %> </p>
<% @idea.categories.each do |category| %>
  Category: <%= category.name %>
<% end %><br>
<% @idea.images.each do |image| %>
  <img src=<%= image.url %> height="100" width="125">
<% end %><br>

<%= link_to "Edit", edit_idea_path %><br>
<%= link_to "Delete", idea_path(@idea), method: "delete"  %><br>
<%= link_to "Back to my user page", user_path(current_user) %>

projects/ideabox/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideabox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    Logged in as <%= current_user.username %>.
    <%= link_to "Logout", logout_path, method: :delete %>
  <% else %>
    <%= link_to "Login", login_path %>
  <% end %>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>

<%= yield %>

</body>
</html>

projects/ideabox/app/views/users/_form.html.erb
<h1>Create an account!</h1>

<%= form_for(@user) do |f|  %>
  <%= f.text_field :first_name, placeholder: "First Name" %><br>
  <%= f.text_field :last_name, placeholder: "Last Name" %><br>
  <%= f.text_field :username, placeholder: "Username" %><br>
  <%= f.password_field :password, placeholder: "password" %><br>
  <%= f.password_field :password_confirmation, placeholder: "password confirmation" %><br>
  <%= f.submit %>
<% end  %>

projects/ideabox/app/views/users/new.html.erb
<%= render 'form' %>

projects/ideabox/app/views/users/show.html.erb
<h1>Welcome, <%= current_user.first_name %>!</h1>

<%= link_to "Create new idea", new_idea_path %><br>

<%= link_to "My ideas", ideas_path %>